/**
 * data.ts — Dashboard data layer
 * ────────────────────────────────
 * All metrics are loaded at runtime from /data/project_data.json
 * (generated by scripts/build_dashboard_data.py from results/).
 * NO hardcoded metric values exist in this file.
 *
 * Unit convention: every metric in project_data.json is already a PERCENTAGE
 * (0–100). Components must render them as-is — never multiply by 100.
 */

// ── Types ────────────────────────────────────────────────────────────────────

export interface HeroStats {
  best_em_gold:          number | null;
  best_f1_gold:          number | null;
  best_em_e2e:           number | null;
  best_f1_e2e:           number | null;
  retrieval_recall:      number | null;
  retrieval_recall_best: number | null;
  retrieval_mrr:         number | null;
  corpus_passages:       number;
  train_examples:        number;
  dev_examples:          number;
  num_models:            number;
}

export interface DatasetStats {
  passages:  number;
  chunks:    number;
  articles:  number;
  avg_words: number;
}

export interface RetrievalChartEntry {
  name:       string;
  "Recall@10": number;
  "Recall@20": number;
  MRR:        number;
  "NDCG@10":  number;
}

export interface QAModelEntry {
  model:           string;
  key:             string;
  params_M:        number;
  em_gold:         number | null;
  f1_gold:         number | null;
  em_e2e:          number | null;
  f1_e2e:          number | null;
  latency_ms:      number | null;
  train_runtime_h: number | null;
  pending:         boolean;
}

export interface ConvergencePoint {
  step:       number;
  epoch:      number;
  train_loss: number | null;
  eval_loss:  number | null;
}

export interface TrainingFacts {
  train_runtime_s:    number;
  train_runtime_h:    number;
  samples_per_second: number;
  total_steps:        number;
  final_train_loss:   number;
  final_eval_loss:    number;
  epochs:             number;
}

/** One row of the per-prediction gold-passage evaluation (results/detailed_eval.json). */
export interface PredictionRow {
  question: string;
  gold:     string;
  pred:     string;
  em:       boolean;
  f1:       number;
  conf:     number;
  lat:      number;
}

export interface DetailedModel {
  key:            string;
  params:         number;
  predictions:    PredictionRow[];
  exact_match:    number;
  f1:             number;
  avg_latency_ms: number;
  avg_confidence: number;
}

export interface DetailedEval {
  device:       string;
  pytorch:      string;
  cuda:         string;
  n_sample:     number;
  generated_at: string;
  models:       Record<string, DetailedModel>;
}

/** One precomputed end-to-end pipeline answer (results/demo_bundle.json). */
export interface DemoAnswer {
  answer:                string;
  answer_start:          number;
  answer_end:            number;
  start_confidence:      number;
  end_confidence:        number;
  avg_confidence:        number;
  latency_ms:            number;
  answer_length_words:   number;
  context_length_words:  number;
  exact_match:           boolean;
  token_f1:              number;
  model_params_million:  number;
}

export interface DemoEntry {
  question:         string;
  topic:            string;
  gold:             string;
  gold_answers:     string[];
  query_complexity: string;
  top_k:            number;
  query_variants:   string[];
  evidence_doc_id:  string;
  evidence_score:   number;
  evidence_text:    string;
  retrieval_hit:    boolean;
  top_chunks:       { doc_id: string; score: number; text: string; rank: number }[];
  answers:          Record<string, DemoAnswer>;
}

export interface QualitativeRow {
  question:          string;
  gold:              string;
  retrieved_passage: string;
  roberta:           string;
  bert:              string;
  distilbert:        string;
}

export interface ProjectData {
  _meta: {
    generated_at: string;
    smoke_test:   boolean | null;
    gpu:          string | null;
    pytorch:      string | null;
    cuda:         string | null;
    run_date:     string | null;
    source:       string | null;
  };
  hero:            HeroStats;
  dataset:         DatasetStats;
  retrieval_chart: RetrievalChartEntry[];
  qa_models:       QAModelEntry[];
  convergence:     Record<string, ConvergencePoint[]>;
  training_facts:  Record<string, TrainingFacts>;
  qualitative:     QualitativeRow[];
  detailed:        DetailedEval;
  demo:            DemoEntry[];
  training_config: Record<string, unknown>;
}

// ── Ablation order (for consistent display) ──────────────────────────────────
export const ABLATION_ORDER = [
  "BM25 only",
  "Dense only",
  "Hybrid (RRF)",
  "+ Re-ranking",
  "+ Adaptive Chunking",
  "+ Multi-Query+RRF",
  "Complete Pipeline",
] as const;

// ── Loader ───────────────────────────────────────────────────────────────────

/**
 * Prefix for files served out of public/. Empty in local dev; set to the repo
 * name when the static export is hosted under a GitHub Pages sub-path.
 * Next rewrites <Link>/<Image> for basePath but NOT fetch() or plain <a href>.
 */
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export function asset(path: string): string {
  return `${BASE_PATH}${path}`;
}

let _cache: ProjectData | null = null;

export async function getProjectData(): Promise<ProjectData> {
  if (_cache) return _cache;
  const res = await fetch(asset("/data/project_data.json"), { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load project_data.json: ${res.status}`);
  _cache = await res.json();
  return _cache!;
}

// ── Derived selectors (all computed from ProjectData) ─────────────────────────

export function getAblationRows(data?: ProjectData): RetrievalChartEntry[] {
  if (!data || !data.retrieval_chart || data.retrieval_chart.length === 0) {
    // Mirror of results/retrieval_progressive.csv — only used if the JSON fetch fails.
    return [
      { name: "BM25 only",           "Recall@10": 86.15, "Recall@20": 89.60, MRR: 69.49, "NDCG@10": 73.39 },
      { name: "Dense only",          "Recall@10": 86.00, "Recall@20": 90.55, MRR: 63.83, "NDCG@10": 68.97 },
      { name: "Hybrid (RRF)",        "Recall@10": 91.50, "Recall@20": 94.60, MRR: 71.70, "NDCG@10": 76.37 },
      { name: "+ Re-ranking",        "Recall@10": 96.25, "Recall@20": 96.65, MRR: 85.25, "NDCG@10": 87.97 },
      { name: "+ Adaptive Chunking", "Recall@10": 91.35, "Recall@20": 94.40, MRR: 71.56, "NDCG@10": 75.64 },
      { name: "+ Multi-Query+RRF",   "Recall@10": 96.25, "Recall@20": 96.70, MRR: 85.19, "NDCG@10": 87.91 },
      { name: "Complete Pipeline",   "Recall@10": 95.95, "Recall@20": 96.45, MRR: 85.20, "NDCG@10": 87.31 },
    ];
  }
  const map = new Map(data.retrieval_chart.map((r) => [r.name, r]));
  return ABLATION_ORDER
    .map((name) => map.get(name))
    .filter((r): r is RetrievalChartEntry => r !== undefined);
}

export function getQAModelRows(data?: ProjectData): QAModelEntry[] {
  if (!data || !data.qa_models || data.qa_models.length === 0) {
    // Mirror of results/qa_model_comparison.csv + e2e_evaluation.csv (3-epoch fine-tuned).
    return [
      { model: "RoBERTa-base",            key: "roberta-base",            params_M: 125, em_gold: 85.38, f1_gold: 91.74, em_e2e: 71.0, f1_e2e: 72.34, latency_ms: 8.3, train_runtime_h: 2.45, pending: false },
      { model: "BERT-base-uncased",       key: "bert-base-uncased",       params_M: 110, em_gold: 80.18, f1_gold: 87.85, em_e2e: 62.0, f1_e2e: 67.54, latency_ms: 7.9, train_runtime_h: 2.33, pending: false },
      { model: "DistilBERT-base-uncased", key: "distilbert-base-uncased", params_M:  66, em_gold: 76.98, f1_gold: 85.52, em_e2e: 60.0, f1_e2e: 62.41, latency_ms: 4.3, train_runtime_h: 1.18, pending: false },
    ];
  }
  return data.qa_models;
}

const FALLBACK_HERO: HeroStats = {
  best_em_gold: 85.38,
  best_f1_gold: 91.74,
  best_em_e2e: 71.0,
  best_f1_e2e: 72.34,
  retrieval_recall: 95.95,
  retrieval_recall_best: 96.25,
  retrieval_mrr: 85.2,
  corpus_passages: 20958,
  train_examples: 87599,
  dev_examples: 10570,
  num_models: 3,
};

export function getHeadlineStats(data?: ProjectData) {
  const h = data?.hero || FALLBACK_HERO;
  const d = data?.dataset;
  return {
    recall10:       h.retrieval_recall ?? FALLBACK_HERO.retrieval_recall!,
    recall10Best:   h.retrieval_recall_best ?? FALLBACK_HERO.retrieval_recall_best!,
    mrr:            h.retrieval_mrr ?? FALLBACK_HERO.retrieval_mrr!,
    bestEM:         h.best_em_gold ?? FALLBACK_HERO.best_em_gold!,
    bestF1:         h.best_f1_gold ?? FALLBACK_HERO.best_f1_gold!,
    bestEME2E:      h.best_em_e2e ?? FALLBACK_HERO.best_em_e2e!,
    bestF1E2E:      h.best_f1_e2e ?? FALLBACK_HERO.best_f1_e2e!,
    totalQAPairs:   (h.train_examples || 87599) + (h.dev_examples || 10570),
    trainPairs:     h.train_examples || 87599,
    devPairs:       h.dev_examples || 10570,
    uniqueContexts: d?.passages || h.corpus_passages || 20958,
    chunks:         d?.chunks || 23288,
    articles:       d?.articles || 490,
    avgContextLen:  d?.avg_words || 117,
    numModels:      h.num_models || 3,
    isSmoke:        data?._meta?.smoke_test ?? false,
    gpu:            data?._meta?.gpu ?? "NVIDIA GeForce RTX 5060 Laptop GPU",
    pytorch:        data?._meta?.pytorch ?? "2.12.0.dev20260408+cu128",
    cuda:           data?._meta?.cuda ?? "12.8",
    runDate:        data?._meta?.run_date ?? "2026-08-16",
  };
}

export function getConvergenceSeries(data: ProjectData) {
  return data.convergence;
}

export function getQualitativeRows(data: ProjectData): QualitativeRow[] {
  return data.qualitative;
}

/** Per-prediction GPU evaluation (results/detailed_eval.json). */
export function getDetailedEval(data?: ProjectData): DetailedEval | null {
  return data?.detailed?.models ? data.detailed : null;
}

/** Precomputed pipeline answers that let the Live Demo run with no backend. */
export function getDemoEntries(data?: ProjectData): DemoEntry[] {
  return data?.demo ?? [];
}

/** Loose match of a free-text question against the precomputed demo set. */
export function matchDemoEntry(entries: DemoEntry[], query: string): DemoEntry | null {
  const norm = (s: string) =>
    s.toLowerCase().replace(/[^\w\s]/g, " ").split(/\s+/).filter(Boolean);
  const STOP = new Set(["what", "who", "when", "where", "which", "how", "why", "is", "are",
                        "was", "were", "the", "a", "an", "of", "in", "on", "at", "to", "for",
                        "did", "does", "do", "by", "with", "and", "or", "it", "that"]);
  const q = norm(query).filter((w) => !STOP.has(w));
  if (q.length === 0) return null;
  let best: DemoEntry | null = null;
  let bestScore = 0;
  for (const e of entries) {
    const t = new Set(norm(e.question).filter((w) => !STOP.has(w)));
    const overlap = q.filter((w) => t.has(w)).length;
    const score = overlap / Math.max(q.length, t.size);
    if (score > bestScore) { bestScore = score; best = e; }
  }
  return bestScore >= 0.5 ? best : null;
}

// ── Legacy synchronous API (server-side, uses embedded fallback from project_data.json) ─────
// These are used by components that haven't migrated to async loading.
// They read from the LAST fetched cache (populated by getProjectData()).

function getDataOrEmpty(): ProjectData | null {
  return _cache;
}

export interface AblationRow {
  config:       string;
  "Recall@10":  number;
  "Recall@20":  number;
  MRR:          number;
  "NDCG@10":    number;
}

export interface QAModelRow {
  model:         string;
  displayName:   string;
  params:        number;
  exactMatch:    number;
  f1:            number;
  e2eExactMatch: number;
  e2eF1:         number;
  isPrimary:     boolean;
}

/** Synchronous — only works after getProjectData() has been called. */
export function getAblationRowsSync(): AblationRow[] {
  const data = getDataOrEmpty();
  if (!data) return [];
  return getAblationRows(data).map((r) => ({
    config:      r.name,
    "Recall@10": r["Recall@10"],
    "Recall@20": r["Recall@20"],
    MRR:         r.MRR,
    "NDCG@10":   r["NDCG@10"],
  }));
}

export function getQAModelRowsSync(): QAModelRow[] {
  const data = getDataOrEmpty();
  if (!data) return [];
  return data.qa_models.map((m) => ({
    model:         m.key,
    displayName:   m.model,
    params:        m.params_M,
    exactMatch:    m.em_gold ?? 0,
    f1:            m.f1_gold ?? 0,
    e2eExactMatch: m.em_e2e ?? 0,
    e2eF1:         m.f1_e2e ?? 0,
    isPrimary:     m.key === "roberta-base",
  }));
}

export function getHeadlineStatsSync() {
  const data = getDataOrEmpty();
  if (!data) return {
    recall10: null, mrr: null, bestEM: null, bestF1: null,
    bestEME2E: null, bestF1E2E: null,
    totalQAPairs: 98169, trainPairs: 87599, devPairs: 10570,
    uniqueContexts: 20958, numModels: 3,
    isSmoke: null, gpu: null, runDate: null,
  };
  return getHeadlineStats(data);
}
